apiVersion: v1
kind: Namespace
metadata:
  name: dev-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-registry
  namespace: dev-registry
  labels:
    app: dev-registry
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dev-registry
  template:
    metadata:
      labels:
        app: dev-registry
    spec:
      containers:
      - image: registry:2
        name: dev-registry
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          hostPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev-registry
  name: dev-registry
  namespace: dev-registry
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5000
    nodePort: 31320
  selector:
    app: dev-registry
  type: NodePort
